create table LINKS_ALREADY_PROCESSED
(
	LINK VARCHAR(2000)
);

create table LINKS_TO_BE_PROCESSED
(
	LINK VARCHAR(2000)
);

create table NEWS
(
	ID BIGINT AUTO_INCREMENT primary key,
	TITLE TEXT,
	CONTENT TEXT,
	URL VARCHAR(2000),
	CREATED_AT TIMESTAMP,
	MODIFIED_AT TIMESTAMP
);